### ISSUE TITLE
Unfamiliar json file

### ISSUE THREAD

**Issue by tcburley** [tcburley/git-test#1]
@douglas-mason what am I supposed to do with the package-lock.json file?

I looked at the documentation and it mentioned it would automatically be ignored but when I pushed my repository to the remote it's still there. Is there are way to manually add it to the .gitignore file or something?

**Comment by douglas-mason** [comment]
no, the lock file isn't auto ignored and also I think should be added to change control (git).  this file ensures that all users with the same repo actually have the same versions of dependencies installed so there's no issues like "oh this works on my machine but not yours because you have an older version of something.js installed"

**Comment by tcburley** [comment]
@douglas-mason Ohhhh okay! So leave it alone then! Thank you

**Comment by douglas-mason** [comment]
You're welcome
